### ISSUE TITLE
have a NullPointerException problem

### ISSUE THREAD

**Issue by ldzSpace** [yongjhih/SwitchPreferenceCompat#4]
java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
05-31 19:03:13.214 15408-15408/com.upay.cleanup_assistant W/System.err:     at android.text.StaticLayout.<init>(StaticLayout.java:49)
05-31 19:03:13.214 15408-15408/com.upay.cleanup_assistant W/System.err:     at android.support.v7.widget.SwitchCompat.makeLayout(SwitchCompat.java:864)
05-31 19:03:13.214 15408-15408/com.upay.cleanup_assistant W/System.err:     at android.support.v7.widget.SwitchCompat.onMeasure(SwitchCompat.java:783)
05-31 19:03:13.214 15408-15408/com.upay.cleanup_assistant W/System.err:     at android.view.View.measure(View.java:17547)
05-31 19:03:13.214 15408-15408/com.upay.cleanup_assistant W/System.err:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
05-31 19:03:13.214 15408-15408/com.upay.cleanup_assistant W/System.err:     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
05-31 19:03:13.214 15408-15408/com.upay.cleanup_assistant W/System.err:     at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
05-31 19:03:13.214 15408-15408/com.upay.cleanup_assistant W/System.err:     at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)

**Comment by yongjhih** [comment]
Did you try the official solution?
`android.support.v7.preference.SwitchPreferenceCompat`
